### ISSUE TITLE
Add a maintainance page

### ISSUE THREAD

**Issue by feeds** [match4everyone/match4everything#5] opened 2020-05-29 11:29 UTC
In general, it would be nice to close the website for maintainance.

## Todo
- page that can be displayed when stuff is not working, preferably with a cool maintainance gif

## Resources
- I guess you could google that

**Comment by Baschdl** [comment] 2020-05-30 19:03
How do we wanna trigger the maintenance mode? A button on the profile page of a superuser?

Do we want a banner notifying our users about the upcoming maintenance?

Need to somehow reroute all our traffic to the maintenance page

**Comment by feeds** [comment] 2020-06-02 08:29
maybe there is also something in the cookiecutter django @kevihiiin mentioned before

**Comment by Baschdl** [comment] 2020-06-15 22:14
There are multiple django packages: https://djangopackages.org/grids/g/maintenance-mode/ 
The most important question is probably if it should be handled by gunicorn or a webserver in front. @maltezacharias Do you have an opinion on this?

**Comment by maltezacharias** [comment] 2020-06-16 22:02
That's a good one, I see lots of argument in favor of the webserver, because it would enable us to do basically anything we want, even switching out the image.

Disadvantage is that such a page would be harder to maintain, because you'd need to mirror the design ideally.

An advantage would be that we could also use it for Gateway Errors,e.g. during failures in the container when gunicorn can't be reached that page (or a similar one) would be displayed automatically. 

I'll think about that. What we should definitely implement is an advance maintenance notice in the app, like a notification bar on top or something like that saying "System will be down for maintenance in xx minutes until 00:00"

**Comment by bjrne** [comment] 2020-06-17 14:41
> preferably with a cool maintainance gif

That's the most important question off all!

- A defunct fire(place)? A fire going extinct?
- Broken matchsticks?

**Comment by maltezacharias** [comment] 2020-06-19 22:03
Current solution in m4h:

![image](https://user-images.githubusercontent.com/9914287/85182263-7c5d3100-b288-11ea-9bbb-29903deffddc.png)

I like it and the image is licensed appropriately that we could ship something like this with our app. A huge downside: Currently I wrote that page manually using bootstrap from a CDN and using our basic design, this needs a better solution, but I fail to see one. 

During the latest go-live I did test this approach. It works fine (502 error in nginx when gunicorn is down) using the following nginx config:

```
        error_page 502 504 /504.html;
        location = /504.html {
            root /var/www/error/;
            #internal;
        }

        location /error-page-resources {
            root /var/www/error/;
            #internal;
        }
```

One big issue however: I ran into problems getting the new version to run. In this scenario one would restart the docker container multiple times and during these phases gunicorn will be running and the nginx error page is not shown intermittently. Do you have a suggestion how we could achieve it, that all normal users are redirected to the error page but devops are able to start the container, connect and verify that it's working and finally let other users connect normally?

What would you propose for this? Is this something we should handle on nginx side (e.g. by only selectively allowing the developer IPs to connect? Use a separate nginx listener on localhost and SSH Tunnel? A maintenance mode with a special cookie or user auth to be able to connect to the site? Something entirely different?

**Comment by Baschdl** [comment] 2020-06-20 11:22
Does gunicorn additionally have the possibility to show a temporary page? This could fix the first problem

**Comment by Baschdl** [comment] 2020-06-20 11:26
How about exposing the website additionally on another port?

**Comment by maltezacharias** [comment] 2020-06-25 23:11
> How about exposing the website additionally on another port?

That' what I meant with "Use a separate nginx listener on localhost and SSH Tunnel?" I wouldn't expose the port on the main IP, but instead make it listen on 127.0.0.1 on the nginx host where you can easily tunnel with ssh.

For turning it on and off, I have done some research, most pages suggest something like checking for existence of a file from the nginx configuration. I think that's wasteful. For now I believe the most practicable way is use to server-configs under /etc/nginx/sites-available/ one called m4e-production and one called m4e-maintenance, a script can then easily be used to switch the sites-enabled symlink between both configs and a server restart can then be issued.

(https://blog.devcloud.hosting/configuring-nginx-for-quickly-switching-to-maintenance-mode-e4136cf497f3, https://serverfault.com/questions/310819/maintenance-page-on-nginx-best-practices)

I think that's about the most elegant way there is. This will always require configuration on the application gateway and I consider it out of scope to detail every possible configuration. We can add this sample config and a minimal page template to this repo and docs. Sound good @Baschdl ?

**Comment by Baschdl** [comment] 2020-07-07 16:27
Why do you want to turn it on and off if it's only visible via a ssh tunnel?

**Comment by maltezacharias** [comment] 2020-07-08 10:50
When you update the image you will typically shut it down and start it up again, then you should do at least a basic testing like "login works" to be sure everything works as intended. If there is a problem during that time (e.g. db fails to start, which has happened more often than I'd like to admit) the users will see an error page instead of maintenance (because Django is available and produces an error message) or even worse login because they get the login page and then might be thrown out if you need to restart the service.

Switchable maintenance page takes care of these problems (and I was glad I had configured it that way on my last updates) as we decide when to show the app page again. Using a ssh tunnel was my idea to be able to test the page and make sure that nobody interferes in that time. 

TBH I think that was too complicated a thought, which is why in production I currently use port 4443 which always shows you the application and ignores the maintenance page. Switching is also solved elegantly by just replacing a symlink for nginx. I will add a section about this to the documentation later. Effectively we've already implemented this, but I think this would be better added to documentation instead of committing further files to the repo

**Comment by Baschdl** [comment] 2020-07-09 18:15
👍 I guess we can close it now @maltezacharias

**Closed as completed** 2020-07-09 18:17 UTC
Labels: deployment
